#!/usr/bin/env bash

# from https://github.com/denysdovhan/dotfiles

# Generate a random password of a given lenght

length="${1:-16}"
openssl rand -base64 "$length" | rev | cut -b 2- | rev | pbcopy
pbpaste
